update page pocket's logo routing for better user experience
chingu-voyages/v46-tier3-team-28 pull request #102
Opened 2023-11-09 15:58 UTC by julichow

2023-11-09 16:55 UTC, Cor4zon requested changes

2023-11-09 16:55 UTC, Cor4zon commented on src/components/Footer/Footer.tsx
> -          <a href="https://v46-tier3-team-28-8mwx.vercel.app/" className="flex items-center gap-2 mb-4 sm:mb-0">
this link will change. Could we use universal solution? Like relative path

2023-11-09 16:55 UTC, Cor4zon commented on src/components/Footer/Footer.tsx
> -          <a href="https://v46-tier3-team-28-8mwx.vercel.app/" className="hover:underline">
same question

2023-11-10 04:37 UTC, Saga-sanga commented on src/components/Footer/Footer.tsx
> -          <a href="https://v46-tier3-team-28-8mwx.vercel.app/" className="flex items-center gap-2 mb-4 sm:mb-0">
just use `href="/"` it will always route to the home no matter the url.

2023-11-10 05:22 UTC, julichow commented on src/components/Footer/Footer.tsx
> -          <a href="https://v46-tier3-team-28-8mwx.vercel.app/" className="flex items-center gap-2 mb-4 sm:mb-0">
Hi @Cor4zon, that should comment was to the old code. Ref to screenshot below, I had pushed with the new code ref href="/". 

 
![image](https://github.com/chingu-voyages/v46-tier3-team-28/assets/118463407/092bd460-665f-44ad-b8d1-cb44e989ca4c)

2023-11-10 05:24 UTC, julichow commented on src/components/Footer/Footer.tsx
> -          <a href="https://v46-tier3-team-28-8mwx.vercel.app/" className="hover:underline">
same with comment above

2023-11-10 06:28 UTC, Saga-sanga approved these changes

2023-11-10 06:29 UTC, Saga-sanga approved these changes

2023-11-10 06:29 UTC, merged