create landing page and navigation bar
chingu-voyages/v46-tier3-team-28 pull request #59
Opened 2023-10-11 13:41 UTC by julichow

2023-10-11 15:37 UTC, Cor4zon requested changes
Good job👍. I've added a few comments

2023-10-11 15:37 UTC, Cor4zon commented on src/app/globals.css
> +  margin-left:90%
Using percentage values for margins isn't a good practice because it can disrupt adaptive design.

2023-10-12 03:47 UTC, julichow commented on src/app/globals.css
> +  margin-left:90%
Fixed margin from % to px

2023-10-12 03:53 UTC, julichow commented on src/app/layout.tsx
> +          {children}</SessionProvider>
Fixed by using ctrl + s manually on keyboard

2023-10-12 03:53 UTC, julichow commented on src/app/page.tsx
> +
Fixed by using ctrl + s manually on keyboard

2023-10-12 04:36 UTC, Saga-sanga commented
Guys, it would be great if we didn't work directly on the development and main branches. There were a lot of conflicts that had to be resolved.

2023-10-17 12:54 UTC, julichow commented on src/components/LoginForm.tsx
> +            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="25" fill="none">
svg import by @christianmacasinagrodriguez

2023-10-17 12:54 UTC, julichow commented on src/components/LoginForm.tsx
> +            <svg xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="none">
same as per above @christianmacasinagrodriguez

2023-10-18 14:02 UTC, christianmacasinagrodriguez commented on src/components/LoginForm.tsx
> +            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="25" fill="none">
The suggestion of Vito is nice since it is best practice. But it seems that the current code of Juli is working. I guess we can resolve this for now then merge it to the branch so that Vito can work on it on his end since he and Juli are working for it.

2023-10-18 15:37 UTC, merged