Fix #82: Fix the styling of the landing page
chingu-voyages/v46-tier3-team-28 pull request #83
Opened 2023-11-02 17:14 UTC by christianmacasinagrodriguez

2023-11-03 05:35 UTC, Saga-sanga requested changes
PR looks good overall. I've mentioned a few of my own personal recommendations.

2023-11-03 05:35 UTC, Saga-sanga commented on next.config.js
> +  },
You can add this config option directly in the nextConfig object.

2023-11-03 05:35 UTC, Saga-sanga commented on src/app/(auth)/login/page.tsx
> +      <main className="w-full h-fit min-h-screen flex items-center justify-start overflow-y-auto flex-col py-10 bg-gray-200">
If you want this component to be affected by dark and light modes I'd recommend using something like `bg-secondary` instead of `bg-gray-200`. You can reference the globals.css file for the possible options

2023-11-03 05:35 UTC, Saga-sanga commented on src/components/LoginForm/LoginForm.tsx
> +        window.location.href = '/dashboard';
I'd recommend using `redirect` instead of `windlow.location.href` since one is a next API and the other is a standard web API. Plus `redirect` will not trigger a refresh only a route change.

2023-11-03 19:14 UTC, christianmacasinagrodriguez commented on next.config.js
> +  },
I really appreciate this. This is a new learning for me. This has been implemented on my new push.

2023-11-03 19:15 UTC, christianmacasinagrodriguez commented on src/app/(auth)/login/page.tsx
> +      <main className="w-full h-fit min-h-screen flex items-center justify-start overflow-y-auto flex-col py-10 bg-gray-200">
It seems that Juli used another way of implementing the dark mode. Will address that later on once our frontend is finished.

2023-11-03 19:16 UTC, christianmacasinagrodriguez commented on src/components/LoginForm/LoginForm.tsx
> +        window.location.href = '/dashboard';
It was previously redirect('/dashboard'); but I was getting an error. So I decided to use the latter. Please help me fix it once this has been merged to the branch. I guess you can fix the error once you pulled my pushes.

2023-11-04 15:16 UTC, Saga-sanga commented on src/components/LoginForm/LoginForm.tsx
> +        window.location.href = '/dashboard';
Sure, will look into it.

2023-11-04 15:17 UTC, Saga-sanga approved these changes

2023-11-04 15:17 UTC, merged